// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXJL-ONzq0xQHICqDt0LbeFDNGK-_ZHNo',
    appId: '1:806505646912:web:15776825a7c5f5cb81c8a5',
    messagingSenderId: '806505646912',
    projectId: 'app-raiz-fe525',
    authDomain: 'app-raiz-fe525.firebaseapp.com',
    storageBucket: 'app-raiz-fe525.firebasestorage.app',
    measurementId: 'G-7S48XXN54P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2EeQ2kUh_vvkg1tsuQ1pHIF0KSWqta84',
    appId: '1:767548996809:android:86a36c5df7725171a0e118',
    messagingSenderId: '767548996809',
    projectId: 'raiz-dos-palmares',
    storageBucket: 'raiz-dos-palmares.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcfFEcpUofVG9dlJPj8dMR_lCwHxBEc78',
    appId: '1:806505646912:ios:166e78dc3bc3c8dd81c8a5',
    messagingSenderId: '806505646912',
    projectId: 'app-raiz-fe525',
    storageBucket: 'app-raiz-fe525.firebasestorage.app',
    iosBundleId: 'com.example.appRaiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcfFEcpUofVG9dlJPj8dMR_lCwHxBEc78',
    appId: '1:806505646912:ios:166e78dc3bc3c8dd81c8a5',
    messagingSenderId: '806505646912',
    projectId: 'app-raiz-fe525',
    storageBucket: 'app-raiz-fe525.firebasestorage.app',
    iosBundleId: 'com.example.appRaiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXJL-ONzq0xQHICqDt0LbeFDNGK-_ZHNo',
    appId: '1:806505646912:web:b7aa0f8066d3b66681c8a5',
    messagingSenderId: '806505646912',
    projectId: 'app-raiz-fe525',
    authDomain: 'app-raiz-fe525.firebaseapp.com',
    storageBucket: 'app-raiz-fe525.firebasestorage.app',
    measurementId: 'G-5TY5B10VDC',
  );
}
